.TH "Car" 3 "Fri Mar 27 2015" "crossroad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Car \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cars\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpid\fP"
.br
.ti -1c
.RI "int \fBroute\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
{ Gada Rezgui and Alexandre FAUCHER} 
.RE
.PP
\fBDate:\fP
.RS 4
23/03/2015 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for crossroad from the source code\&.
