.TH "/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/cars.h" 3 "Fri Mar 27 2015" "crossroad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/cars.h \- cars header  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'carrefour\&.h'\fP
.br
\fC#include 'ipcTools\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCar\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCar\fP \fBgenereCar\fP (int route)"
.br
.RI "\fIControl the cars process\&. \fP"
.ti -1c
.RI "\fBCar\fP \fBgenereCarRandomly\fP (int valMax, int nbCarsMax)"
.br
.ti -1c
.RI "void \fBcarsCrossroad\fP (\fBCar\fP car)"
.br
.in -1c
.SH "Detailed Description"
.PP 
cars header 


.SH "Function Documentation"
.PP 
.SS "\fBCar\fP genereCar (int route)"

.PP
Control the cars process\&. 
.PP
\fBAuthor:\fP
.RS 4
{ Gada REZGUI and Alexandre FAUCHER} 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for crossroad from the source code\&.
