.TH "/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/readFileRegex.h" 3 "Fri Mar 27 2015" "crossroad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/readFileRegex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <regex\&.h>\fP
.br
\fC#include 'carrefour\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreadFile\fP (char *filename, int *nbCarsMax, int *valMaxTimeToWaitForCreatingCar)"
.br
.RI "\fIread from a file informations, then analyse them with the regular expression \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void readFile (char * filename, int * nbCarsMax, int * valMaxTimeToWaitForCreatingCar)"

.PP
read from a file informations, then analyse them with the regular expression 
.PP
\fBAuthor:\fP
.RS 4
{ Gada REZGUI and Alexandre FAUCHER} 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for crossroad from the source code\&.
