.TH "/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/readFileRegex.c" 3 "Fri Mar 27 2015" "crossroad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/gadarezgui/Documents/cours/L3-INFO/S6/os/OS-Project/readFileRegex.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'readFileRegex\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_ERROR_MSG\fP   0x1000"
.br
.RI "\fIreaf from a file informations, then analyse them with the regular expression \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBreadFile\fP (char *filename, int *nbCarsMax, int *valMaxTimeToWaitForCreatingCar)"
.br
.RI "\fIread from a file informations, then analyse them with the regular expression \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_ERROR_MSG   0x1000"

.PP
reaf from a file informations, then analyse them with the regular expression 
.PP
\fBAuthor:\fP
.RS 4
{ Gada REZGUI and Alexandre FAUCHER} 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void readFile (char * filename, int * nbCarsMax, int * valMaxTimeToWaitForCreatingCar)"

.PP
read from a file informations, then analyse them with the regular expression 
.PP
\fBAuthor:\fP
.RS 4
{ Gada REZGUI and Alexandre FAUCHER} 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for crossroad from the source code\&.
