.TH "Shared" 3 "Fri Mar 27 2015" "crossroad" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shared \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumberOfCarsInCrossroads\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "int \fBnumberOfAllCarCreated\fP"
.br
.ti -1c
.RI "int \fBfirstRoadLights\fP"
.br
.ti -1c
.RI "int \fBsecondRoadLights\fP"
.br
.ti -1c
.RI "int \fBnbCarWaitingFirstRoadLights\fP"
.br
.ti -1c
.RI "int \fBnbCarWaitingSecondRoadLights\fP"
.br
.ti -1c
.RI "int \fBtimeToWaitRoadLights\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int end"
end of the program 
.SS "int firstRoadLights"
indique the color of the roadLight, in the primary road\&. 
.SS "int numberOfAllCarCreated"
we use it in the cars' index 
.SS "int numberOfCarsInCrossroads"
numberOfCarsInCrossroad = 0 mean that they are no car in the crossroad numberOfCarsInCrossroad != 0 they are cars 
.SS "int secondRoadLights"
indique the color of the roadLight, in the primary road\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for crossroad from the source code\&.
